name: Build and publish image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Create and use docker context
        run: |
          docker context create multi-provider-toolbox
          docker context use multi-provider-toolbox

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: multi-provider-toolbox

      - name: Set up docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push new image
        run: |
          docker buildx build --push --tag ghcr.io/berops/multi-provider-toolbox/multi-provider-toolbox:latest -f ./Dockerfile .
